const sharedCareerModule = {
  id: "career-launch",
  stage: "career",
  title: "Portfolio Story & Career Readiness",
  domain: "Career Readiness",
  type: "Career lab",
  hours: 6,
  skills: ["Portfolio", "Communication"],
  description: "Turn your completed work into a clear portfolio story and an interview-ready growth plan.",
  objectives: ["Present evidence of your skills", "Explain project decisions clearly", "Plan the next 90 days"],
  topics: ["Portfolio narrative", "STAR examples", "Skill evidence", "Interview practice"],
  activity: "Create a one-page portfolio case study and record a five-minute project walkthrough.",
};

const TRACK_MODULES = {
  tech: [
    { id: "ml-foundations", stage: "foundation", title: "Applied ML Foundations", domain: "ML Fundamentals", type: "Course + lab", hours: 10, skills: ["Python", "Machine Learning"], description: "Build a practical base in supervised learning, data preparation, and model selection.", objectives: ["Prepare model-ready data", "Select a baseline algorithm", "Explain bias and variance"], topics: ["Feature preparation", "Regression", "Classification", "Bias-variance trade-off"], activity: "Train and compare two baseline models on a public dataset." },
    { id: "model-evaluation", stage: "foundation", title: "Reliable Model Evaluation", domain: "Model Evaluation", type: "Practice lab", hours: 8, skills: ["Metrics", "Experimentation"], description: "Evaluate models with metrics that reflect the real business problem.", objectives: ["Choose task-appropriate metrics", "Detect class imbalance", "Validate without leakage"], topics: ["Precision and recall", "F1 and ROC-AUC", "Cross-validation", "Leakage"], activity: "Build an evaluation report for an imbalanced classifier." },
    { id: "neural-networks", stage: "core", title: "Neural Networks & Transformers", domain: "Neural Networks", type: "Guided project", hours: 14, skills: ["PyTorch", "Transformers"], description: "Understand modern neural networks and implement a small transformer-based workflow.", objectives: ["Explain attention", "Build a training loop", "Compare pretrained models"], topics: ["Backpropagation", "Embeddings", "Attention", "Transformers"], activity: "Fine-tune a compact pretrained model for text classification." },
    { id: "rag-architecture", stage: "core", title: "RAG & AI Application Architecture", domain: "AI Architecture", type: "System design lab", hours: 12, skills: ["LLMs", "RAG", "Vector Search"], description: "Design grounded AI applications with retrieval, prompting, validation, and observability.", objectives: ["Design a RAG pipeline", "Choose chunking and retrieval strategies", "Reduce unsupported answers"], topics: ["Embeddings", "Vector databases", "Context injection", "Output validation"], activity: "Create an architecture and clickable demo for a document question-answering assistant." },
    { id: "mlops-delivery", stage: "applied", title: "MLOps Delivery Pipeline", domain: "MLOps", type: "Hands-on lab", hours: 14, skills: ["Docker", "CI/CD", "Model Serving"], description: "Package, test, and serve an ML model through a repeatable delivery pipeline.", objectives: ["Containerize a model", "Expose a prediction endpoint", "Automate quality checks"], topics: ["Docker", "REST serving", "CI/CD", "Model registry"], activity: "Containerize a model API and define its CI validation workflow." },
    { id: "production-monitoring", stage: "applied", title: "Production Monitoring & Drift", domain: "MLOps", type: "Operations simulation", hours: 9, skills: ["Monitoring", "Drift Detection"], description: "Monitor model health and respond when data or performance changes.", objectives: ["Define service and model metrics", "Detect drift", "Plan retraining triggers"], topics: ["Data drift", "Concept drift", "Alerting", "Retraining policy"], activity: "Design a monitoring dashboard and incident response playbook." },
    { id: "ai-engineer-capstone", stage: "capstone", title: "End-to-End AI Engineer Capstone", domain: "AI Architecture", type: "Portfolio project", hours: 20, skills: ["Architecture", "Deployment", "Evaluation"], description: "Combine application design, model evaluation, deployment, and monitoring in one portfolio project.", objectives: ["Ship an end-to-end prototype", "Document design trade-offs", "Demonstrate measurable quality"], topics: ["Problem framing", "Architecture", "Evaluation", "Deployment"], activity: "Build and present a deployable AI application with an evaluation report." },
    sharedCareerModule,
  ],
  data: [
    { id: "modern-ml", stage: "foundation", title: "Modern Machine Learning Refresh", domain: "Advanced ML", type: "Course + notebook", hours: 10, skills: ["Machine Learning", "Feature Engineering"], description: "Refresh model selection, feature engineering, and robust validation for modern data work.", objectives: ["Build strong baselines", "Prevent leakage", "Compare model families"], topics: ["Boosting", "Feature engineering", "Validation", "Calibration"], activity: "Create a reproducible model comparison notebook." },
    { id: "experiment-design", stage: "foundation", title: "Experiment Design & Causal Thinking", domain: "Experiment Design", type: "Analytics lab", hours: 9, skills: ["A/B Testing", "Statistics"], description: "Design experiments that separate practical impact from statistical noise.", objectives: ["Define a test hypothesis", "Estimate sample size", "Interpret uncertainty"], topics: ["Power", "Significance", "Effect size", "Guardrail metrics"], activity: "Write and analyze an A/B test plan for a product change." },
    { id: "llm-data-workflows", stage: "core", title: "LLM Workflows for Data Teams", domain: "GenAI / LLMs", type: "Guided project", hours: 12, skills: ["LLMs", "RAG", "Prompting"], description: "Use language models for extraction, classification, and grounded analytics workflows.", objectives: ["Design structured prompts", "Evaluate generated outputs", "Build a grounded workflow"], topics: ["Prompt schemas", "RAG", "Evaluation sets", "Structured outputs"], activity: "Build a document-to-insight pipeline with an evaluation sample." },
    { id: "explainable-ai", stage: "core", title: "Explainability, Fairness & Governance", domain: "AI Ethics & Governance", type: "Case workshop", hours: 9, skills: ["SHAP", "Fairness", "Governance"], description: "Explain predictions and validate model behavior across important user groups.", objectives: ["Create local explanations", "Test fairness metrics", "Document model limitations"], topics: ["SHAP", "Equalized odds", "Model cards", "Risk controls"], activity: "Produce a model card with explainability and fairness evidence." },
    { id: "data-mlops", stage: "applied", title: "Data-to-Model Production Workflow", domain: "MLOps & Deployment", type: "Hands-on lab", hours: 13, skills: ["Pipelines", "Docker", "Monitoring"], description: "Move a reproducible analysis into a monitored production workflow.", objectives: ["Package transformations", "Version data and models", "Monitor data quality"], topics: ["Feature pipelines", "Model registry", "Serving", "Drift"], activity: "Package a training and inference pipeline with validation checks." },
    { id: "decision-storytelling", stage: "applied", title: "Decision Storytelling with AI", domain: "Experiment Design", type: "Communication lab", hours: 7, skills: ["Data Storytelling", "Decision Support"], description: "Translate analysis and model evidence into a decision-ready recommendation.", objectives: ["Frame a decision", "Communicate uncertainty", "Recommend measurable action"], topics: ["Executive summaries", "Uncertainty", "Visual evidence", "Recommendations"], activity: "Present a six-slide decision memo based on model evidence." },
    { id: "data-science-capstone", stage: "capstone", title: "Applied Data Science Capstone", domain: "Advanced ML", type: "Portfolio project", hours: 20, skills: ["Experimentation", "ML", "Communication"], description: "Solve a realistic data problem from framing through validation and stakeholder recommendation.", objectives: ["Create a reproducible solution", "Defend evaluation choices", "Communicate impact"], topics: ["Problem framing", "Data quality", "Modeling", "Decision memo"], activity: "Complete and present an end-to-end data science case study." },
    sharedCareerModule,
  ],
  nontech: [
    { id: "ai-literacy", stage: "foundation", title: "Practical AI Literacy", domain: "AI Concepts", type: "Short course", hours: 6, skills: ["AI Literacy", "Critical Thinking"], description: "Understand what AI can do, where it fails, and how it fits into everyday work.", objectives: ["Distinguish predictive and generative AI", "Recognize limitations", "Choose suitable use cases"], topics: ["AI basics", "Generative AI", "Hallucinations", "Human oversight"], activity: "Map five tasks from your role to appropriate AI and non-AI approaches." },
    { id: "data-confidence", stage: "foundation", title: "Data Confidence for Business", domain: "Data Literacy", type: "Practice workshop", hours: 7, skills: ["Data Literacy", "Analytics"], description: "Read data critically and ask the questions needed before acting on AI-generated insights.", objectives: ["Interpret basic metrics", "Spot weak evidence", "Validate AI summaries"], topics: ["Data quality", "Averages", "Correlation", "Validation"], activity: "Review a sample dashboard and write a decision-quality checklist." },
    { id: "prompt-workflows", stage: "core", title: "Prompting for Reliable Work", domain: "Prompt Engineering", type: "Hands-on practice", hours: 8, skills: ["Prompting", "Communication"], description: "Create clear, reusable prompts with context, constraints, and quality checks.", objectives: ["Write structured prompts", "Iterate using feedback", "Verify generated work"], topics: ["Role and context", "Examples", "Constraints", "Output formats"], activity: "Build a reusable prompt pack for three recurring work tasks." },
    { id: "ai-toolkit", stage: "core", title: "AI Tools & Workflow Automation", domain: "AI Tools", type: "Workflow lab", hours: 9, skills: ["AI Tools", "Automation"], description: "Combine AI tools with human review to improve a real business workflow.", objectives: ["Select the right tool", "Design review checkpoints", "Measure time saved"], topics: ["Research", "Summarization", "Content workflows", "Automation"], activity: "Redesign one weekly workflow and compare before/after time and quality." },
    { id: "responsible-use", stage: "applied", title: "Responsible AI in Daily Work", domain: "Ethical Awareness", type: "Scenario workshop", hours: 7, skills: ["Ethics", "Privacy", "Governance"], description: "Use AI responsibly around sensitive data, bias, copyright, and accountability.", objectives: ["Identify risky inputs", "Review biased outputs", "Escalate appropriately"], topics: ["Privacy", "Bias", "Copyright", "Accountability"], activity: "Create a responsible-use checklist for your team." },
    { id: "business-use-case", stage: "applied", title: "AI Business Use-Case Design", domain: "AI Concepts", type: "Business design lab", hours: 8, skills: ["Use-case Design", "ROI"], description: "Frame an AI opportunity with a clear user, workflow, metric, and safety boundary.", objectives: ["Define the problem", "Estimate value", "Plan human oversight"], topics: ["Use-case canvas", "Success metrics", "Feasibility", "Risk"], activity: "Complete and present an AI use-case canvas for your function." },
    { id: "ai-workflow-capstone", stage: "capstone", title: "AI-Enabled Workflow Capstone", domain: "AI Tools", type: "Portfolio project", hours: 14, skills: ["Prompting", "Workflow Design", "Measurement"], description: "Build a documented, measurable AI-assisted workflow for a realistic business task.", objectives: ["Design a repeatable workflow", "Include human review", "Measure quality and time"], topics: ["Workflow mapping", "Prompt library", "Quality rubric", "Impact"], activity: "Demonstrate an AI-assisted workflow with a before/after impact report." },
    sharedCareerModule,
  ],
  manager: [
    { id: "ai-strategy", stage: "foundation", title: "AI Strategy & Opportunity Portfolio", domain: "AI Strategy", type: "Strategy workshop", hours: 8, skills: ["AI Strategy", "Prioritization"], description: "Translate business strategy into a prioritized portfolio of feasible AI opportunities.", objectives: ["Identify suitable opportunities", "Score value and feasibility", "Sequence investments"], topics: ["Use-case discovery", "Portfolio scoring", "Data readiness", "Roadmaps"], activity: "Create a ranked portfolio of five AI opportunities." },
    { id: "ai-economics", stage: "foundation", title: "AI Value, ROI & Metrics", domain: "ROI & Metrics", type: "Business case lab", hours: 7, skills: ["ROI", "Metrics"], description: "Build defensible AI business cases using baselines, impact measures, and total cost.", objectives: ["Define a baseline", "Estimate total cost", "Choose balanced metrics"], topics: ["Cost-to-serve", "Revenue impact", "Risk reduction", "Adoption"], activity: "Build a one-page AI investment case with assumptions and measures." },
    { id: "governance-operating-model", stage: "core", title: "Responsible AI Governance", domain: "Risk & Governance", type: "Governance lab", hours: 10, skills: ["Governance", "Risk", "Compliance"], description: "Design decision rights, controls, and evidence for responsible AI delivery.", objectives: ["Classify risks", "Assign accountability", "Define review gates"], topics: ["Risk tiers", "Model cards", "Human oversight", "Audit evidence"], activity: "Draft a lightweight AI governance playbook for one use case." },
    { id: "vendor-evaluation", stage: "core", title: "AI Vendor & Platform Evaluation", domain: "Vendor Evaluation", type: "Decision workshop", hours: 8, skills: ["Procurement", "Architecture", "Risk"], description: "Evaluate AI vendors across value, data, integration, security, and operating risk.", objectives: ["Define evaluation criteria", "Run evidence-based scoring", "Identify lock-in risks"], topics: ["Technical fit", "Data terms", "Security", "Total cost"], activity: "Create and apply a vendor scorecard to two example solutions." },
    { id: "ai-team-model", stage: "applied", title: "Leading Cross-Functional AI Teams", domain: "Team Leadership", type: "Operating-model lab", hours: 9, skills: ["Leadership", "Operating Model"], description: "Structure teams and rituals that connect product, data, engineering, risk, and domain experts.", objectives: ["Define team roles", "Set delivery rituals", "Manage technical debt"], topics: ["Hub-and-spoke", "Product teams", "RACI", "Delivery health"], activity: "Design a team charter and responsibility map for an AI initiative." },
    { id: "ai-scale", stage: "applied", title: "From Pilot to Responsible Scale", domain: "AI Strategy", type: "Scaling simulation", hours: 9, skills: ["Change Management", "Adoption", "Operations"], description: "Plan adoption, monitoring, change management, and governance for scaling beyond a pilot.", objectives: ["Set scale gates", "Plan workforce adoption", "Track value realization"], topics: ["Pilot criteria", "Adoption", "Monitoring", "Benefits realization"], activity: "Write a 90-day plan to move an AI pilot into controlled production." },
    { id: "ai-transformation-capstone", stage: "capstone", title: "AI Transformation Plan Capstone", domain: "AI Strategy", type: "Executive project", hours: 16, skills: ["Strategy", "Governance", "Leadership"], description: "Combine opportunity, governance, operating model, and value into an executive-ready transformation plan.", objectives: ["Create an actionable roadmap", "Balance value and risk", "Secure stakeholder alignment"], topics: ["Vision", "Portfolio", "Governance", "Operating model", "Metrics"], activity: "Present a twelve-month AI transformation plan to a mock executive committee." },
    sharedCareerModule,
  ],
};

export const LEARNING_STAGES = [
  { id: "foundation", name: "Foundation", description: "Close essential knowledge gaps and establish a dependable base." },
  { id: "core", name: "Core Skills", description: "Build the role-specific skills used in real work." },
  { id: "applied", name: "Applied Practice", description: "Combine skills through practical, decision-focused activities." },
  { id: "capstone", name: "Capstone", description: "Produce evidence of your ability through an end-to-end project." },
  { id: "career", name: "Career Readiness", description: "Translate new skills into a portfolio and next-step plan." },
];

export function getTrackModules(personaId) {
  return TRACK_MODULES[personaId] || TRACK_MODULES.tech;
}
