export const COURSE_CATALOG = [
  { id: "ml-baselines", title: "Machine Learning Foundations in Practice", provider: "Pathwise Lab", mark: "PL", instructor: "Pathwise curriculum team", level: "Developing", format: "Course + lab", duration: "10 hours", hours: 10, rating: 4.8, learners: "18K", price: "Free", accent: "#2563EB", skills: ["Python", "Machine Learning", "Feature Engineering"], moduleIds: ["ml-foundations"], description: "Build reliable baseline models and learn the core workflow behind practical machine learning.", outcomes: ["Prepare data for modeling", "Train baseline models", "Explain bias and variance"], syllabus: ["Data preparation", "Regression and classification", "Validation basics", "Baseline comparison"] },
  { id: "metrics-lab", title: "Model Evaluation & Metrics Lab", provider: "DataCraft", mark: "DC", instructor: "Anika Rao", level: "Intermediate", format: "Practice lab", duration: "8 hours", hours: 8, rating: 4.9, learners: "24K", price: "Free", accent: "#14B8A6", skills: ["Metrics", "Experimentation", "Statistics"], moduleIds: ["model-evaluation", "experiment-design"], description: "Choose the right model metrics and identify misleading results before they reach production.", outcomes: ["Use precision, recall and F1", "Handle class imbalance", "Prevent validation leakage"], syllabus: ["Metric selection", "Imbalanced data", "Cross-validation", "Evaluation report"] },
  { id: "transformer-workshop", title: "Transformers with PyTorch", provider: "Hugging Face", mark: "🤗", instructor: "Sylvain Gugger", level: "Advanced", format: "Guided project", duration: "14 hours", hours: 14, rating: 4.9, learners: "87K", price: "Free", accent: "#10B981", skills: ["PyTorch", "Transformers", "Deep Learning"], moduleIds: ["neural-networks"], description: "Learn modern transformer concepts through a compact text-classification implementation.", outcomes: ["Explain attention", "Use pretrained models", "Fine-tune a classifier"], syllabus: ["Embeddings", "Attention", "Training loops", "Fine-tuning"] },
  { id: "rag-system-design", title: "RAG Application System Design", provider: "DeepLearning.AI", mark: "DL", instructor: "AI applications team", level: "Advanced", format: "System design lab", duration: "12 hours", hours: 12, rating: 4.8, learners: "41K", price: "Free", accent: "#7C3AED", skills: ["LLMs", "RAG", "Vector Search"], moduleIds: ["rag-architecture", "llm-data-workflows"], description: "Design a grounded retrieval-augmented application that can be evaluated and improved.", outcomes: ["Design a RAG pipeline", "Select retrieval strategies", "Evaluate answer quality"], syllabus: ["Embeddings", "Retrieval", "Prompting", "Evaluation"] },
  { id: "mlops-docker", title: "Docker & CI/CD for Machine Learning", provider: "Google Cloud", mark: "GC", instructor: "MLOps learning team", level: "Advanced", format: "Hands-on lab", duration: "14 hours", hours: 14, rating: 4.8, learners: "32K", price: "Free", accent: "#F59E0B", skills: ["Docker", "CI/CD", "Model Serving"], moduleIds: ["mlops-delivery", "data-mlops"], description: "Package a machine-learning service and establish repeatable checks for delivery.", outcomes: ["Containerize a model", "Expose a prediction API", "Create CI checks"], syllabus: ["Docker basics", "Model serving", "Testing", "CI pipeline"] },
  { id: "monitoring-playbook", title: "ML Monitoring & Drift Playbook", provider: "Evidently", mark: "EV", instructor: "Production ML team", level: "Advanced", format: "Operations simulation", duration: "9 hours", hours: 9, rating: 4.7, learners: "12K", price: "Free", accent: "#0EA5E9", skills: ["Monitoring", "Drift Detection", "MLOps"], moduleIds: ["production-monitoring", "data-mlops"], description: "Create the signals and response plan needed to maintain an ML system after deployment.", outcomes: ["Detect data drift", "Define alerts", "Plan retraining triggers"], syllabus: ["Service metrics", "Drift", "Alerts", "Incident response"] },
  { id: "ab-testing", title: "A/B Testing for Product Decisions", provider: "DataCamp", mark: "DC", instructor: "Rafael Irizarry", level: "Intermediate", format: "Analytics lab", duration: "9 hours", hours: 9, rating: 4.7, learners: "112K", price: "Free", accent: "#14B8A6", skills: ["A/B Testing", "Statistics", "Analytics"], moduleIds: ["experiment-design", "decision-storytelling"], description: "Design experiments and explain practical impact with appropriate statistical confidence.", outcomes: ["Define hypotheses", "Estimate sample sizes", "Interpret uncertainty"], syllabus: ["Hypotheses", "Power", "Effect size", "Decision memo"] },
  { id: "responsible-ai", title: "Responsible AI & Model Governance", provider: "Microsoft Learn", mark: "MS", instructor: "Responsible AI team", level: "Intermediate", format: "Case workshop", duration: "9 hours", hours: 9, rating: 4.8, learners: "56K", price: "Free", accent: "#2563EB", skills: ["Governance", "Fairness", "Model Cards"], moduleIds: ["explainable-ai", "governance-operating-model", "responsible-use"], description: "Apply practical governance, fairness, and documentation controls to an AI use case.", outcomes: ["Document limitations", "Assess fairness", "Set review controls"], syllabus: ["Fairness", "Model cards", "Risk tiers", "Human oversight"] },
  { id: "prompt-library", title: "Prompt Engineering for Workflows", provider: "Open Practice", mark: "OP", instructor: "Prompt design team", level: "Developing", format: "Hands-on practice", duration: "8 hours", hours: 8, rating: 4.8, learners: "29K", price: "Free", accent: "#EC4899", skills: ["Prompting", "Communication", "AI Tools"], moduleIds: ["prompt-workflows", "ai-toolkit"], description: "Create reusable prompts with context, examples, constraints, and simple quality checks.", outcomes: ["Write structured prompts", "Create reusable templates", "Review AI outputs"], syllabus: ["Prompt components", "Examples", "Constraints", "Quality rubrics"] },
  { id: "ai-use-case", title: "AI Use-Case Design & Value Canvas", provider: "Pathwise Lab", mark: "PL", instructor: "Strategy curriculum team", level: "Developing", format: "Business design lab", duration: "8 hours", hours: 8, rating: 4.7, learners: "16K", price: "Free", accent: "#F97316", skills: ["Use-case Design", "ROI", "AI Literacy"], moduleIds: ["business-use-case", "ai-strategy", "ai-economics"], description: "Frame a valuable AI opportunity with users, metrics, risks, and operating constraints.", outcomes: ["Frame a use case", "Estimate value", "Plan human oversight"], syllabus: ["Problem framing", "Value canvas", "Risk", "Success metrics"] },
  { id: "ai-vendor-scorecard", title: "AI Vendor Evaluation Scorecard", provider: "StrategyWorks", mark: "SW", instructor: "Enterprise AI team", level: "Advanced", format: "Decision workshop", duration: "8 hours", hours: 8, rating: 4.6, learners: "9K", price: "Free", accent: "#DC2626", skills: ["Procurement", "Risk", "Architecture"], moduleIds: ["vendor-evaluation"], description: "Evaluate AI vendors with evidence across data, integration, cost, and governance.", outcomes: ["Build an evaluation scorecard", "Identify vendor risk", "Compare total cost"], syllabus: ["Requirements", "Security", "Data terms", "Scoring"] },
  { id: "portfolio-story", title: "Portfolio Storytelling & Interview Practice", provider: "Pathwise Lab", mark: "PL", instructor: "Career readiness team", level: "All levels", format: "Career lab", duration: "6 hours", hours: 6, rating: 4.9, learners: "21K", price: "Free", accent: "#6366F1", skills: ["Portfolio", "Communication", "Interviewing"], moduleIds: ["career-launch"], description: "Transform completed learning work into clear, credible portfolio evidence and interview stories.", outcomes: ["Write a portfolio case study", "Prepare STAR examples", "Plan a 90-day growth cycle"], syllabus: ["Narrative", "Evidence", "Interview stories", "Next steps"] },
];

export const COURSE_LEVELS = ["All", "Developing", "Intermediate", "Advanced"];
export const COURSE_FORMATS = ["All", ...new Set(COURSE_CATALOG.map((course) => course.format))];
export const COURSE_PROVIDERS = ["All", ...new Set(COURSE_CATALOG.map((course) => course.provider))];

export function getCourseById(courseId) {
  return COURSE_CATALOG.find((course) => course.id === courseId) || null;
}

// Percentage of this course's skill coverage that matches the target skills.
// Courses curated directly for a module get a 70% floor since the link itself is evidence of relevance.
export function getCourseMatchScore(course, targetSkills = [], moduleId = null) {
  const normalizedTargets = new Set(targetSkills.map((skill) => skill.toLowerCase()));
  const matchedSkills = course.skills.filter((skill) => normalizedTargets.has(skill.toLowerCase()));
  const linkedByModule = moduleId ? course.moduleIds.includes(moduleId) : false;
  if (!matchedSkills.length && !linkedByModule) return 0;
  const skillScore = course.skills.length ? Math.round((matchedSkills.length / course.skills.length) * 100) : 0;
  return linkedByModule ? Math.max(skillScore, 70) : skillScore;
}

export function getCoursesForModule(moduleId, skills = []) {
  const normalizedSkills = skills.map((skill) => skill.toLowerCase());
  return COURSE_CATALOG
    .filter((course) =>
      course.moduleIds.includes(moduleId) ||
      course.skills.some((skill) => normalizedSkills.includes(skill.toLowerCase())),
    )
    .map((course) => ({ ...course, matchScore: getCourseMatchScore(course, skills, moduleId) }))
    .sort((a, b) => b.matchScore - a.matchScore);
}
