import { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Badge, GlassCard } from "../../components/UIKit";
import { T } from "../../theme";
import { useRecommendations, useRefreshRecommendations } from "../../hooks";
import { getInstructorNames, getPlatformStyle } from "./courseDisplay";

const BADGE_VARIANT = {
  "AI Best Fit": "violet",
  Popular: "blue",
  "Best Rated": "green",
  "Fast Track": "amber",
};

// Phase B22: adapted-backend already had a full AI recommendation engine
// (services/recommendationService.js - fuzzy-matches the catalog against the
// learner's onboarding goals/interests, then an LLM shortlists + badges the
// result) generated by a separate background worker
// (workers/recommendationWorker.js) - but nothing in the frontend ever called
// it. useRecommendations()/useRefreshRecommendations() (hooks/index.js) sat
// unused. This is the first UI consumer.
export function RecommendationsPanel() {
  const { data, refetch } = useRecommendations();
  const { execute: refresh, loading: refreshing } = useRefreshRecommendations();
  const navigate = useNavigate();
  const pollRef = useRef(null);

  const courses = data?.data || [];
  const meta = data?.meta;

  // The backend never does the AI work inline (see recommendationController.js) -
  // it schedules the worker and returns immediately with whatever it already
  // has, so a first-time or expired batch needs polling until the worker
  // finishes. `meta.pollAfterMs` is the backend's own suggested interval.
  useEffect(() => {
    if (!meta) return undefined;
    if (meta.status !== "generating" && !meta.shouldGenerate) return undefined;

    pollRef.current = setTimeout(() => refetch(), meta.pollAfterMs || 25000);
    return () => clearTimeout(pollRef.current);
  }, [meta?.status, meta?.shouldGenerate, meta?.pollAfterMs, refetch]);

  const handleRefresh = async () => {
    await refresh();
    refetch();
  };

  if (!meta) return null;

  const isGeneratingFirstBatch = meta.status === "generating" && courses.length === 0;

  if (isGeneratingFirstBatch) {
    return (
      <GlassCard className="fade-up" style={{ marginBottom: 20, padding: 24, textAlign: "center" }}>
        <p style={{ fontSize: 13, color: T.muted, margin: 0 }}>Building your personalized recommendations… this can take a minute.</p>
      </GlassCard>
    );
  }

  if (courses.length === 0) return null;

  return (
    <GlassCard className="fade-up" style={{ marginBottom: 20 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: T.faint, textTransform: "uppercase", letterSpacing: "0.1em", fontFamily: "'General Sans'" }}>Recommended for you</div>
        <button type="button" className="btn-ghost" style={{ fontSize: 11.5, padding: "6px 14px" }} onClick={handleRefresh} disabled={refreshing}>
          {refreshing || meta.refreshing ? "Refreshing…" : "Refresh"}
        </button>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 14 }}>
        {courses.slice(0, 6).map((course) => {
          const { mark, accent } = getPlatformStyle(course.platform);
          return (
            <div
              key={course.id}
              onClick={() => navigate(`/courses/${course.id}`)}
              style={{ cursor: "pointer", padding: 16, borderRadius: 14, background: "rgba(255,255,255,0.5)", border: "1px solid rgba(255,255,255,0.6)" }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
                <div style={{ width: 30, height: 30, borderRadius: 9, background: `linear-gradient(135deg, ${accent}18, ${accent}08)`, border: `1px solid ${accent}20`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, color: accent }}>{mark}</div>
                <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                  {(course.badges || []).map((badge) => <Badge key={badge} variant={BADGE_VARIANT[badge] || "muted"}>{badge}</Badge>)}
                </div>
              </div>
              <div style={{ fontSize: 13.5, fontWeight: 700, color: T.navy, marginBottom: 4, lineHeight: 1.3 }}>{course.title}</div>
              <div style={{ fontSize: 11.5, color: T.muted }}>{getInstructorNames(course.instructors)}</div>
            </div>
          );
        })}
      </div>
    </GlassCard>
  );
}
